version: "3.7"

services:
  api:
    image: rof20004/ajuda-api
    container_name: ajuda-api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_NAME=postgres
      - ENV=local
    depends_on:
      - db
    networks:
      - ajuda-network

  db:
    image: postgres
    container_name: ajuda-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ajuda-db:/var/lib/postgresql/data/
    networks:
      - ajuda-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ajuda-db:

networks:
  ajuda-network:
